# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Update changelog

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

env:
  branch: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout specific branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ env.branch }}
      - name: Set up Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
      - name: Update changelog
        run: |
          npm i auto-changelog --no-save
          npx auto-changelog
      - name: Commit changed files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          git status
          git commit -m "ci: update CHANGELOG.md"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.branch }}
