# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: GitHub CI - Create a Release

on:
  workflow_dispatch:
  push:
    branches:
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@leanup'
      # - name: Dry install and pack
      #   run: |
      #     npx lerna exec --ignore @template/* --stream -- npm install --only=dev
      #     npx lerna exec --ignore @template/* --stream -- npm pack
      # // https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#fromjson
      - name: Read Lerna
        id: lerna
        run: |
          content=`cat ./lerna.json | tr -d "\n"`
          echo "::set-output name=lernaJson::$content"
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: 'You can find more details about the changes here: https://github.com/leanupjs/leanup/blob/master/CHANGELOG.md#${{fromJson(steps.lerna.outputs.lernaJson).version}}'
          draft: true
          prerelease: false
          release_name: Release ${{fromJson(steps.lerna.outputs.lernaJson).version}}
          tag_name: ${{fromJson(steps.lerna.outputs.lernaJson).version}}
