# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test all framework variants

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        default: latest
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@leanup'
      - name: Test all framework variants (${{github.event.inputs.version}})
        shell: bash
        run: |
          rm ../.eslintrc.js
          bash ./wake-up-all.sh ${{github.event.inputs.version}}
        working-directory: scripts
