# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Increment version (Prerelease)

on:
  workflow_dispatch:

env:
  level: prerelease

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Increment version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npx lerna version ${{ env.level }} --no-push --yes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_PUSH_TOKEN }}
