# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Increment version (Patch)

on:
  workflow_dispatch:

env:
  level: patch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
      - name: Increment version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npx lerna version ${{ env.level }} --no-push --yes
      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GIT_PUSH_TOKEN }}
      #     branch: ${{ github.ref }}
      # - name: Read Lerna
      #   id: lerna
      #   run: |
      #     content=`cat ./lerna.json | tr -d "\n"`
      #     echo "::set-output name=lernaJson::$content"
      # - name: Create Release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     body: 'You can find more details about the changes here: https://github.com/leanupjs/leanup/blob/master/CHANGELOG.md#${{fromJson(steps.lerna.outputs.lernaJson).version}}'
      #     draft: true
      #     prerelease: false
      #     release_name: Release ${{fromJson(steps.lerna.outputs.lernaJson).version}}
      #     tag_name: ${{fromJson(steps.lerna.outputs.lernaJson).version}}
