# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test all Node.js and NPM variants

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch
        default: release/1.1
        required: true
      tag:
        description: Tag
        default: next
        required: true
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    # continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        node: [10, 12, 14, 15]
        # https://github.com/actions/virtual-environments#available-environments
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Node.js v${{ matrix.node }} on OS (${{ matrix.os }})
    steps:
      - name: Checkout specific branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Set up Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm run update
      - name: Test all framework variants
        run: sh wake-up-all.sh ${{github.event.inputs.tag}}
        working-directory: scripts
