# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: NPM v5 Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

env:
  branch: release/1.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout specific branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ env.branch }}
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Install and update dependencies
        run: npm run update
      - name: Test all framework variants
        run: sh wake-up-all.sh ${{env.tag}}
        working-directory: scripts
