# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: GitHub CI - Publish to NPM (DRY)

on:
  workflow_dispatch:
  # release:
  #   types:
  #     - published

env:
  access: public
  alias: leanupjs
  registry: https://npm.pkg.github.com
  tag: canary
  token: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # https://unix.stackexchange.com/questions/112023/how-can-i-replace-a-string-in-a-files
      - name: Replace alias in all package.json's
        run: |
          find packages -name "*.js" -type f -exec sed -i -e "s/@leanup/@${{env.alias}}/g" {} +
          find packages -name "*.json" -type f -exec sed -i -e "s/@leanup/@${{env.alias}}/g" {} +
          find packages -name "*.ts" -type f -exec sed -i -e "s/@leanup/@${{env.alias}}/g" {} +
          find packages -name "*.tsx" -type f -exec sed -i -e "s/@leanup/@${{env.alias}}/g" {} +
          git diff
      - name: Set up Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '14.x'
          registry-url: '${{env.registry}}'
          scope: '@${{env.alias}}'
      - name: Install and publish only @${{env.alias}}/cli-core-e2e
        run: |
          ls -la
          npm install
          npm publish --access=${{env.access}} --tag=${{env.tag}} || true
        working-directory: packages/cli/core/e2e
        env:
          NODE_AUTH_TOKEN: ${{env.token}}
      - name: Install and publish only @${{env.alias}}/cli-core-format
        run: |
          npm install
          npm publish --access=${{env.access}} --tag=${{env.tag}} || true
        working-directory: packages/cli/core/format
        env:
          NODE_AUTH_TOKEN: ${{env.token}}
      - name: Install and publish only @${{env.alias}}/cli-core-lint
        run: |
          npm install
          npm publish --access=${{env.access}} --tag=${{env.tag}} || true
        working-directory: packages/cli/core/lint
        env:
          NODE_AUTH_TOKEN: ${{env.token}}
      - name: Install and publish only @${{env.alias}}/cli-core-test
        run: |
          npm install
          npm publish --access=${{env.access}} --tag=${{env.tag}} || true
        working-directory: packages/cli/core/test
        env:
          NODE_AUTH_TOKEN: ${{env.token}}
      - name: Install and publish only @${{env.alias}}/cli
        run: |
          npm install
          npm publish --access=${{env.access}} --tag=${{env.tag}} || true
        working-directory: packages/cli/core
        env:
          NODE_AUTH_TOKEN: ${{env.token}}
      - name: Install and publish only @${{env.alias}}/lib
        run: |
          npm install
          npm publish --access=${{env.access}} --tag=${{env.tag}} || true
        working-directory: packages/lib
        env:
          NODE_AUTH_TOKEN: ${{env.token}}
      - name: Install and publish non @${{env.alias}}/cli, @${{env.alias}}/cli-core-e2e, @${{env.alias}}/cli-core-format, @${{env.alias}}/cli-core-lint, @${{env.alias}}/cli-core-test and @${{env.alias}}/lib
        run: |
          npx lerna exec --ignore @template/* --ignore @${{env.alias}}/cli --ignore @${{env.alias}}/cli-core-e2e --ignore @${{env.alias}}/cli-core-format --ignore @${{env.alias}}/cli-core-lint --ignore @${{env.alias}}/cli-core-test --ignore @${{env.alias}}/lib --stream -- npm install
          npx lerna exec --ignore @template/* --ignore @${{env.alias}}/cli --ignore @${{env.alias}}/cli-core-e2e --ignore @${{env.alias}}/cli-core-format --ignore @${{env.alias}}/cli-core-lint --ignore @${{env.alias}}/cli-core-test --ignore @${{env.alias}}/lib --no-bail --stream -- npm publish --access=${{env.access}} --tag=${{env.tag}} || true
        env:
          NODE_AUTH_TOKEN: ${{env.token}}
      - name: Test all framework variants
        run: |
          rm ../.eslintrc.js
          sh wake-up-all.sh ${{env.alias}} ${{env.tag}}
        working-directory: scripts
        env:
          NODE_AUTH_TOKEN: ${{env.token}}
